name: data_check
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  - pandas=2.1.4
  - pytest=7.4.0
  - scipy=1.11.4
  - pip=23.3.1
  - mlflow==2.8.1
  - pip:
        - wandb==0.16.0
